# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: qdrtech
# "service" is the name of this project. This will also be added to your AWS resource names.
service: typescript-serverless-template

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
